name: Rebuild ruby

on:
  workflow_dispatch:
    inputs:
      ruby_version:
        description: "Ruby version"
        required: true
        default: "2.7.2"
      base_version:
        description: "Base version"
        required: false
      rubygems_version:
        description: "Rubygems version"
        required: false

permissions: {}

jobs:
  rebuild:
    runs-on: ubuntu-latest

    steps:
      - id: tag
        run: printf "name=v$(echo $VERSION | tr '.' '_')" >> $GITHUB_OUTPUT
        shell: bash
        env:
          VERSION: ${{ github.event.inputs.ruby_version }}

      - name: Install base ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ github.event.inputs.base_version || github.event.inputs.ruby_version }}

      - name: Install rubygems
        if: github.event.inputs.rubygems_version
        run: gem update --system ${VERSION}
        env:
          VERSION: ${{ github.event.inputs.rubygems_version }}

      # https://cache.ruby-lang.org/pub/ruby/3.4/ruby-3.4.2.zip
      - name: Download release tarball
        run: |
          curl -L --fail https://cache.ruby-lang.org/pub/ruby/${VERSION%.*}/ruby-${VERSION}.tar.gz -o ruby-${VERSION}.tar.gz
        env:
          VERSION: ${{ github.event.inputs.ruby_version }}

      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          repository: ruby/ruby
          ref: ${{ steps.tag.outputs.name }}
          path: ruby
          fetch-depth: 0 # needed for changelog generation

      - name: Make snapshot
        run: |
          ./autogen.sh
          mkdir build
          pushd build
          ../configure
          make dist V=1 DISTOPTS="-packages=gzip"
        working-directory: ruby
        env:
          RELNAME: ${{ github.event.inputs.ruby_version }}

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5

      - name: Diff against released tarball
        run: |
          uvx diffoscope ruby-${RELNAME}.tar.gz ruby/build/tmp/ruby-${RELNAME}.tar.gz \
            --html-dir ruby-${RELNAME}-diff \
            --html ruby-${RELNAME}-diff.html \
            --markdown ruby-${RELNAME}-diff.md \
            || true
        env:
          RELNAME: ${{ github.event.inputs.ruby_version }}

      - name: Upload HTML dir diff
        uses: actions/upload-artifact@v4
        with:
          name: diff-html-dir
          include-hidden-files: true
          path: ruby-${{github.event.inputs.ruby_version }}-diff

      - name: Upload HTML diff
        uses: actions/upload-artifact@v4
        with:
          name: diff-html
          include-hidden-files: true
          path: ruby-${{github.event.inputs.ruby_version }}-diff.html

      - name: Upload markdown diff
        uses: actions/upload-artifact@v4
        with:
          name: diff-markdown
          path: ruby-${{github.event.inputs.ruby_version }}-diff.md

      - name: Upload rebuilt tarball
        uses: actions/upload-artifact@v4
        with:
          name: tarball
          path: ruby/build/tmp/ruby-${{github.event.inputs.ruby_version }}.tar.gz

      - name: Set output
        run: |
          cat \
            <(printf '# Ruby: %s\n' $VERSION) \
            <(printf 'Base: \n' $BASE) \
            <(printf 'RubyGems: \n' $(gem --version)) \
            <(printf '```yaml\n') ruby/build/tmp/info/info.yml <(printf '\n```\n\n') \
            ruby-$VERSION-diff.md \
            >> $GITHUB_STEP_SUMMARY
        env:
          VERSION: ${{ github.event.inputs.ruby_version }}
          BASE: ${{ github.event.inputs.base_version || github.event.inputs.ruby_version }}
          RUBYGEMS: ${{ github.event.inputs.rubygems_version }}
